fix(ui): TE-2284 section headers for template properties
startreedata/thirdeye pull request #1427
Opened 2024-05-15 17:19 UTC by harshilvelotio

#### Issue(s)

https://startree.atlassian.net/browse/TE-2284

#### Description

- Added section headers for each template properties

#### Screenshots

Uploading TemplatePropertySections.mp4…

#### How to test
- Go to "Create Alert"
- Switch to Advanced view

2024-05-15 20:11 UTC, cyrilou242 requested changes
added notes in jira: 
https://startree.atlassian.net/browse/TE-2284?focusedCommentId=30205

2024-05-21 08:43 UTC, alcatraz627 commented on thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-properties-builder/alert-template-properties-builder.component.tsx
> +// const PropertySectionHeader = withStyles<
Do we want to keep this code or remove it?

2024-05-21 09:09 UTC, alcatraz627 approved these changes
Looks fine overall, added a couple of code cleanup comments

2024-05-21 10:03 UTC, cyrilou242 approved these changes
feature wise LGTM

2024-05-21 17:41 UTC, merged