[server] Fix rca default aggregation fn logic
startreedata/thirdeye pull request #1520
Opened 2024-08-09 08:35 UTC by anshul98ks123

#### Issue(s)

[RobinHood - for alerts using SUM, RCA/investigation is using COUNT](https://startree.atlassian.net/browse/TE-2382)

#### Description

Aggregation function for RCA heatmap is resolved by following logic currently:
1. If custom RCA aggregation fn is provided, use it
2. if metric does not exists, default to COUNT 
3. else, use default aggregation fn of the metric

In cases 2 and 3, alert aggregation function should be used for RCA heatmap if custom rca aggregation fn is not present in template properties

This PR introduces changes to include a new metadata property in alert template - detectionAggregationFunction, which will be set to the alert aggregation function. It is being used to decide aggregation fn for rca heatmap if custom rca aggregation fn is not provided

#### Test
Scenario: An alert which is based on MAX aggregation function, but the metric's default aggregation fn is SUM

Before:
In absence of custom rca aggregation fn, we are using metric's default aggregation (SUM) for rca heatmap
![screencapture-localhost-7004-root-cause-analysis-v2-anomaly-56389-investigate-what-where-page-2024-08-09-13_21_22](https://github.com/user-attachments/assets/626c3b9d-2bdc-427f-b0be-5d11cedec805)

After:
In absence of custom rca aggregation fn, we will now use alert aggregation fn (MAX) for rca heatmap
![screencapture-localhost-7004-root-cause-analysis-v2-anomaly-56376-investigate-what-where-page-2024-08-09-13_04_10](https://github.com/user-attachments/assets/f0c2d76a-7d5b-492d-825b-8b0e85cc6508)

2024-08-09 09:14 UTC, cyrilou242 requested changes

2024-08-09 09:14 UTC, cyrilou242 commented on thirdeye-server/src/main/java/ai/startree/thirdeye/rca/RcaInfoFetcher.java
>            .setName(metricName)
I think we can skip fetching from the persistence layer altogether.
The long term plan is to use this metric abstraction less and less and eventually remove it. (it has other issues, like ThirdEye needs to maintain the metrics in sync with the table schema).

So I think we can just construct the metricConfigDTO manually likes it's done line 144. 
```
metricConfigDTO = new MetricConfigDTO()
           .setDataset(datasetName)
          .setName(metricName)
          .setDefaultAggFunction(
         optional(metadataMetricDTO.getDefaultAggregationFunction).orElse(
         optional(alertMetadataDto.getDetectionAggregationFunction()).orElse(COUNT));
```

2024-08-09 09:14 UTC, cyrilou242 commented on thirdeye-server/src/main/java/ai/startree/thirdeye/rca/RcaInfoFetcher.java
>            .setName(metricName)
note this will change the logic to fetch the dataset below, we will need to fetch by name, namespace in all cases (this is fine)

2024-08-09 09:33 UTC, anshul98ks123 commented
Makes sense. Addressed the comments

2024-08-09 10:18 UTC, cyrilou242 commented on thirdeye-server/src/main/java/ai/startree/thirdeye/rca/RcaInfoFetcher.java
> +    final DatasetConfigDTO datasetConfigDto = datasetDAO.findByNameAndNamespaceOrUnsetNamespace(
please use findUniqueByNameAndNamespace 
(I think)

2024-08-09 13:41 UTC, cyrilou242 requested changes

2024-08-09 14:06 UTC, anshul98ks123 commented
Addressed review comments

2024-08-12 10:35 UTC, cyrilou242 approved these changes
LGTM thanks!

2024-08-12 10:56 UTC, merged