fix(ui): TE-2461 send datasetEndTime in rerun anomaly detection
startreedata/thirdeye pull request #1568
Opened 2024-09-26 05:21 UTC by nalin-patidar

#### Issue(s)

https://startree.atlassian.net/browse/TE-2461

#### Description

In rerun anomaly detection, the endTime was being sent incorrectly as defaultStartTime. Fixed it to use datasetEndTime

2024-09-26 09:41 UTC, cyrilou242 requested changes

2024-09-26 09:41 UTC, cyrilou242 commented on thirdeye-ui/src/app/locale/languages/en-us.json
> +        "anomaly-detection-task-ran-successfully": "Anomaly detection task ran successfully",
the task run is async. 

I think we should have something like
```
"Anomaly detection rerun task created successfully. Completion may take a few minutes."

2024-10-04 07:04 UTC, jayeshchoudhary approved these changes

2024-10-04 07:23 UTC, cyrilou242 approved these changes
lgtm thanks!

2024-10-04 10:28 UTC, merged