[kubernetes] Allow MySQL instance to be external
startreedata/thirdeye pull request #978
Opened 2023-02-18 00:30 UTC by dd-willgan

#### Issue(s)

[List links to the issues being addressed.](https://github.com/startreedata/thirdeye/issues/977)

#### Description

- Use `condition` on the MySQL subchart so that local MySQL doesn't have to be deployed
- Add `.Values.mysql.mysqlUrl` so that external URL can be provided
- Updated configmaps so that `mysqlUrl` is used if provided

#### Screenshots

N/A

#### How to test

From `kubernetes/helm/startree-thirdeye`, I ran the following with different values of `mysql.enabled` and `mysql.mysqlUrl`. Saw working.

```
helm install --dry-run --debug thirdeye . > dry-run.txt
```

2023-02-18 00:53 UTC, mmantri2022 reviewed
Looks good to me. As long as we have ensured no security risk involved.

2023-02-18 00:54 UTC, mmantri2022 approved these changes
looks good to me as long as there is no security issues with this and right measure and password protection is taken care.

2023-02-20 04:52 UTC, shounakmk219 requested changes
Nice addition! just few comments. 
You may also want to make changes at the [backup job](https://github.com/startreedata/thirdeye/blob/0d1a8011bbeb580ff5c7fdc86eccfa7344a06b70/kubernetes/helm/startree-thirdeye/templates/mysql/mysql-backup-cronjob.yaml#L51) so that it points to the right mysql instance.

2023-02-20 04:52 UTC, shounakmk219 commented on kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml
> +      {{ if .Values.mysql.mysqlUrl }}
The condition should be on `.Values.mysql.enabled`. That will force user to provide the `mysqlUrl` when internal mysql is disabled. Also avoid the situation of thirdeye connecting to external mysql as well as spinning its own instance if `mysql.mysqlUrl` is also set and `mysql.enabled` is also set to `true`. Let me know your thoughts.

2023-02-20 04:52 UTC, shounakmk219 commented on kubernetes/helm/startree-thirdeye/templates/scheduler/scheduler-config.yaml
> +      {{ if .Values.mysql.mysqlUrl }}
Same comment as above

2023-02-20 04:52 UTC, shounakmk219 commented on kubernetes/helm/startree-thirdeye/templates/worker/worker-config.yaml
> +      {{ if .Values.mysql.mysqlUrl }}
Same comment as above

2023-02-21 17:43 UTC, shounakmk219 approved these changes

2023-02-21 17:43 UTC, merged